# Generated by Django 3.0.7 on 2020-06-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
