# Generated by Django 3.0.7 on 2020-06-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prueba_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
