# Generated by Django 3.0.7 on 2020-06-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200628_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prueba',
            new_name='Document',
        ),
    ]
